---
title: "CompMusic Porftolio"
author: "Natalia Zawada"
date: "21/02/2021"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: columns
    storyboard: true
    theme: lumen
---

```{r}
library(tidyverse)
library(spotifyr)
library(flexdashboard)
library(ggthemes)
library(ggplot2)
library(plotly)
library(dplyr)


```

Introduction
=========================================

> <center>Please do not show this portfolio in class</center>

```{r, echo=FALSE}

my_id <- 'natzaw'


detriot <- get_playlist_audio_features(my_id, "7zJxmBOEVValZYC0zmfLrf")
chicago <- get_playlist_audio_features(my_id, "5ZixL1Pb2mzyED9hSQ8y2G")
europe  <- get_playlist_audio_features(my_id, "1YnOhBchUwaRFOqzWZp4CV")

```
Visualization {.storyboard}
=========================================

### Danceability vs Energy 

```{r, echo=FALSE}

ggplot(detriot, (aes(energy, danceability, color = key, size = tempo ))) +
  geom_point() +
  ggtitle("Detriot")

ggplot(chicago, (aes(energy, danceability, color = key, size = tempo))) +
  geom_point() + 
  ggtitle("Chicago")

ggplot(europe, (aes(energy, danceability, color = key, size = tempo))) +
  geom_point() + 
  ggtitle("Berlin")
```

***

Commentary Here

### Valence vs Loudness

```{r, echo=FALSE}
ggplot(detriot, (aes(valence, loudness, color = mode))) +
  geom_point() +
  ggtitle("Detriot")

ggplot(chicago, (aes(valence, loudness, color = mode))) +
  geom_point() + 
  ggtitle("Chicago")

ggplot(europe, (aes(valence, loudness, color = mode))) +
  geom_point() + 
  ggtitle("Berlin")
```

***

Commentary Here

### Chart 3

```{r, echo=FALSE}

```

***

Commentary Here


Discussion
=========================================

Discussion Here




